import { GoogleGenAI } from '@google/genai';
import { ClinicalDecisionResponse, ConsultationRequest } from '../types/index.js';
import { loadConfig } from '../config.js';
import { getSystemPrompt } from '../protocols/manager.js';

export interface ClinicalAiResult {
  response: ClinicalDecisionResponse;
  rawText: string;
  model: string;
}

export class ClinicalAiUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ClinicalAiUnavailableError';
  }
}

export class GoogleClinicalAi {
  private readonly client: GoogleGenAI;
  private readonly model: string;

  constructor(apiKey = loadConfig().googleApiKey, model = loadConfig().clinicalAiModel) {
    if (!apiKey) {
      throw new ClinicalAiUnavailableError('GOOGLE_API_KEY or GEMINI_API_KEY is required for backend clinical AI inference');
    }
    this.client = new GoogleGenAI({ apiKey });
    this.model = model;
  }

  async consult(request: ConsultationRequest): Promise<ClinicalAiResult> {
    const prompt = buildClinicalPrompt(request);
    const result = await this.client.models.generateContent({
      model: this.model,
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        temperature: 0.1,
      },
    });

    const rawText = result.text || '';
    return {
      response: parseClinicalDecision(rawText),
      rawText,
      model: this.model,
    };
  }
}

export function buildClinicalPrompt(request: ConsultationRequest): string {
  return [
    getSystemPrompt(request.country, request.language),
    'Return one JSON object that exactly matches the SHIFA ClinicalDecision schema.',
    'Use only these decision values: TREAT, REFER_URGENT, REFER_ROUTINE, MONITOR.',
    'Patient and symptoms:',
    JSON.stringify(request, null, 2),
  ].join('\n\n');
}

export function parseClinicalDecision(rawText: string): ClinicalDecisionResponse {
  const parsed = JSON.parse(extractJsonObject(rawText));
  assertClinicalDecision(parsed);
  return parsed;
}

function extractJsonObject(rawText: string): string {
  const trimmed = rawText.trim();
  if (trimmed.startsWith('{') && trimmed.endsWith('}')) return trimmed;

  const start = trimmed.indexOf('{');
  const end = trimmed.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) {
    throw new Error('Clinical AI response did not contain a JSON object');
  }
  return trimmed.slice(start, end + 1);
}

function assertClinicalDecision(value: any): asserts value is ClinicalDecisionResponse {
  const validDecisions = new Set(['TREAT', 'REFER_URGENT', 'REFER_ROUTINE', 'MONITOR']);
  if (!value || typeof value !== 'object') throw new Error('Clinical AI response is not an object');
  if (typeof value.id !== 'string') value.id = `ai-${Date.now()}`;
  if (!validDecisions.has(value.decision)) throw new Error('Clinical AI response has an invalid decision');
  if (typeof value.primaryDiagnosis !== 'string') throw new Error('Clinical AI response is missing primaryDiagnosis');
  if (!Array.isArray(value.differentialDiagnoses)) value.differentialDiagnoses = [];
  if (typeof value.confidence !== 'number') throw new Error('Clinical AI response is missing numeric confidence');
  if (!Array.isArray(value.dangerSigns)) value.dangerSigns = [];
  if (typeof value.reasoningTrace !== 'string') value.reasoningTrace = 'Generated by configured Google clinical AI model.';
  if (typeof value.voiceResponse !== 'string') throw new Error('Clinical AI response is missing voiceResponse');
}

export default GoogleClinicalAi;
